@extends('layouts.app')
@section('title', 'Finalizar compra')

@section('content')
<header class="page-header compact"><div class="container"><span class="eyebrow text-light">Paso final</span><h1>Finalizar compra</h1><p>Transacción de demostración: no realiza cargos reales.</p></div></header>
<div class="container section-space">
    <form method="POST" action="{{ route('checkout.store') }}" id="checkout-form" novalidate>
        @csrf
        <div class="row g-5">
            <div class="col-lg-7">
                <section class="checkout-panel"><span class="step-number">1</span><h2 class="h4">Datos de entrega</h2><div class="row g-3 mt-1"><div class="col-md-6"><label class="form-label" for="customer_name">Nombre de quien recibe</label><input class="form-control" id="customer_name" name="customer_name" value="{{ old('customer_name', $user->name) }}" maxlength="120" required></div><div class="col-md-6"><label class="form-label" for="customer_phone">Teléfono</label><input class="form-control" id="customer_phone" name="customer_phone" value="{{ old('customer_phone', $user->phone) }}" maxlength="30" autocomplete="tel" required></div><div class="col-12"><label class="form-label" for="shipping_address">Dirección exacta</label><textarea class="form-control" id="shipping_address" name="shipping_address" rows="3" minlength="10" maxlength="500" required>{{ old('shipping_address', $user->address) }}</textarea></div></div></section>
                <section class="checkout-panel mt-4"><span class="step-number">2</span><h2 class="h4">Método de pago</h2><div class="payment-options mt-3"><label class="payment-option"><input type="radio" name="payment_method" value="card" @checked(old('payment_method', 'card') === 'card')><span><strong>Tarjeta</strong><small>Crédito o débito</small></span></label><label class="payment-option"><input type="radio" name="payment_method" value="paypal" @checked(old('payment_method') === 'paypal')><span><strong>PayPal</strong><small>Cuenta de demostración</small></span></label></div>
                    <div id="card-fields" class="payment-fields"><div class="row g-3"><div class="col-12"><label class="form-label" for="card_holder">Nombre en la tarjeta</label><input class="form-control" id="card_holder" name="card_holder" value="{{ old('card_holder') }}" autocomplete="cc-name" maxlength="120"></div><div class="col-12"><label class="form-label" for="card_number">Número</label><input class="form-control" id="card_number" name="card_number" value="{{ old('card_number') }}" inputmode="numeric" autocomplete="cc-number" maxlength="23" placeholder="4111 1111 1111 1111"><div class="form-text">Use 4111 1111 1111 1111 para la demostración.</div></div><div class="col-6"><label class="form-label" for="card_expiry">Vence</label><input class="form-control" id="card_expiry" name="card_expiry" value="{{ old('card_expiry') }}" inputmode="numeric" autocomplete="cc-exp" maxlength="5" placeholder="MM/AA"></div><div class="col-6"><label class="form-label" for="card_cvv">CVV</label><input class="form-control" type="password" id="card_cvv" name="card_cvv" inputmode="numeric" autocomplete="cc-csc" maxlength="4" placeholder="123"></div></div></div>
                    <div id="paypal-fields" class="payment-fields d-none"><label class="form-label" for="paypal_email">Correo de PayPal</label><input class="form-control" type="email" id="paypal_email" name="paypal_email" value="{{ old('paypal_email') }}" autocomplete="email"><div class="form-text">Se aprobará de forma simulada.</div></div>
                    <div class="privacy-callout mt-3">Los campos de tarjeta se validan durante la solicitud y se descartan. La base de datos solo conserva los últimos cuatro dígitos.</div>
                </section>
            </div>
            <aside class="col-lg-5"><div class="summary-card sticky-summary"><h2 class="h4">Su pedido</h2>@foreach($items as $item)<div class="checkout-item"><span>{{ $item['quantity'] }} × {{ $item['product']->name }}</span><strong>₡{{ number_format($item['line_total'], 0, ',', '.') }}</strong></div>@endforeach<hr><dl><div><dt>Subtotal</dt><dd>₡{{ number_format($totals['subtotal'], 0, ',', '.') }}</dd></div><div><dt>IVA (13%)</dt><dd>₡{{ number_format($totals['tax'], 0, ',', '.') }}</dd></div><div><dt>Envío</dt><dd>{{ $totals['shipping'] ? '₡'.number_format($totals['shipping'], 0, ',', '.') : 'Gratis' }}</dd></div><div class="summary-total"><dt>Total</dt><dd>₡{{ number_format($totals['total'], 0, ',', '.') }}</dd></div></dl><button class="btn btn-primary btn-lg w-100" type="submit">Confirmar y pagar</button><p class="summary-help">Al confirmar acepta el procesamiento simulado del pago.</p></div></aside>
        </div>
    </form>
</div>
@endsection
